### ISSUE TITLE
pdf支持点击事件吗？

### ISSUE THREAD

**Issue by zavier006** [lidong1665/AndroidPDF#1]
https://github.com/JoanZapata/android-pdfview 我记得这个pdfview不支持点击事件，真是遗憾，不知道你的是否可以支持pdfview的OnClickListener

**Comment by lidong1665** [comment]
要给什么增加点击事件呢？



lidong1665@163.com
 
发件人： zhenyuehong
发送时间： 2016-12-30 16:11
收件人： lidong1665/AndroidPDF
抄送： Subscribed
主题： [lidong1665/AndroidPDF] pdf支持点击事件吗？ (#1)
https://github.com/JoanZapata/android-pdfview 我记得这个pdfview不支持点击事件，真是遗憾，不知道你的是否可以支持pdfview的OnClickListener

**Comment by zavier006** [comment]
要给整个pdfview增加点击事件，我记得之前有个项目有这样的需求，点击pdfview，然后隐藏除PDFview之外的所有layout，然后我试着获取pdfview.setOnClickListener()，结果发现点击事件不起作用

**Comment by lidong1665** [comment]
有时间了尝试一下。
